name: Generate PDF with mdpdf

on[push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install mdpdf
      run: npm install -g mdpdf

    - name: Convert resume.md to PDF
      run: mdpdf resume.md -o resume.pdf

    - name: List files
      run: ls -lh
