name: Generate PDF with mdpdf

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex fonts-noto-cjk

    - name: Convert markdown to PDF
      run: pandoc resume.md -o resume.pdf --pdf-engine=xelatex -V mainfont="Noto Sans CJK SC"

    - name: List files
      run: ls -lh
