name: Generate PDF Resume with markdown-pdf

on:
  push:
    paths:
      - 'resume.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install markdown-pdf globally
      run: npm install -g markdown-pdf

    - name: Convert resume.md to PDF
      run: markdown-pdf resume.md -o resume.pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume-pdf
        path: resume.pdf
